### ISSUE TITLE
Syslog not properly detected when "/dev/log" is a socket

### ISSUE THREAD

**Issue by ChrisArgyle** [thesharp/daemonize#27]
The method start() does not initialize the logging object properly due to its use of the os.path.isfile() method which returns false on sockets.  Linux systems use a socket for /dev/log so this prevents daemonize from correctly choosing handlers.SysLogHandler for the logging object.  Offending line below.

https://github.com/thesharp/daemonize/blob/a5f7ad8da9a6f9094ee06a99043a051671ceb5fa/daemonize.py#L145

**Comment by thesharp** [comment]
Fixed in master.
