### ISSUE TITLE
add posibility to add custom action when daemon dies by SIGTERM

### ISSUE THREAD

**Issue by tantra35** [thesharp/daemonize#30]
Its will be very useful when program use SocketServer. For example within this action we can make server shutdown and unlink socket file(if server uses AF_UNIX sockets)

**Comment by thesharp** [comment]
Hi @tantra35.

I will look into it in about a day.

But right now you can achieve what you want with overloading the `sigterm()` method. If you would do this, don't forget to execute stuff which is already inside it (e.g. clean pid, etc).

**Comment by thesharp** [comment]
I looked into it and decided that the correct way to do what you want is via overload.
