### ISSUE TITLE
Error on os.remove if user is changed

### ISSUE THREAD

**Issue by jbarlow83** [thesharp/daemonize#34]
If a script is launched as root and it calls `Daemonize(... user='notroot'... )` to execute the daemon with non-root permissions, then .pid file will be created by as owned by root since that happens early in setup.

But when the daemon exits, an exception occurs because the nonroot user attempts to delete the root-owned file.

I believe correct behavior would be to change ownership of the .pid file to the daemon user prior to the daemon giving up its root privileges.

Stack trace
```
KeyboardInterrupt
Stopping daemon.
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/atexit.py", line 24, in _run_exitfuncs
    func(*targs, **kargs)
  File "/usr/local/lib/python2.7/site-packages/daemonize.py", line 71, in exit
    os.remove(self.pid)
OSError: [Errno 13] Permission denied: '/var/run/test.pid'
```

**Comment by thesharp** [comment]
@jbarlow83 thanks for reporting that issue. It's been fixed in 2.4.2 version on PyPI.
