### ISSUE TITLE
Error on exit

### ISSUE THREAD

**Issue by citosid** [thesharp/daemonize#43]
I have this code:

```python
daemon = Daemonize(
    app="Encoder",
    pid=pid_file,
    action=self.__daemonize,
    foreground=False if self.env == 'production' else True,
    logger=logging
)
daemon.start()
```

And in the exit handler for the process (when someone either hits ctrl-c or run the stop process):

```python
with open(pid_file, 'r') as content_file:
    pid = content_file.read()
os.kill(int(pid), signal.SIGTERM)
```

That works ok, but when it exists (although it executes everything ok) I see this error:

```
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/daemonize.py", line 71, in exit
    os.remove(self.pid)
FileNotFoundError: [Errno 2] No such file or directory: '/var/run/encoder.pid'
```

Reading the code, I see this:

```python
        signal.signal(signal.SIGTERM, self.sigterm)
        atexit.register(self.exit)
```

And that has this:

```python
    def sigterm(self, signum, frame):
        """
        These actions will be done after SIGTERM.
        """
        self.logger.warn("Caught signal %s. Stopping daemon." % signum)
        os.remove(self.pid)
        sys.exit(0)

    def exit(self):
        """
        Cleanup pid file at exit.
        """
        self.logger.warn("Stopping daemon.")
        os.remove(self.pid)
        sys.exit(0)
```

If I understand the code correctly, that will try to delete the pid file twice, is that right? Am I doing something wrong?

**Comment by vyscond** [comment]
1 - `sys.exit(0)` makes the python application terminates. I think you confusing it with the `exit(self)`.
2 - did you checked that the encoder.pid is being created? If it's created than something else is removing it before you can reach the sigterm or exit handlers

**Comment by citosid** [comment]
The PID is created, and it is deleted. I debug the app, and it is deleted at `sigterm` method. Then, the `self.exit` method is executed and that tries to delete again the file that was deleted by the `self.sigterm` method.

**Comment by vyscond** [comment]
well how the hell you can call `self.exit` after a `sys.exit(0)`?  Anyways just insert on your build:

```python
try:
    os.remove(self.pid)
except OSError:
    print('pid file already removed')
```

**Comment by thesharp** [comment]
Hey @citosid 

Could you try your thing with the lastest code from master or 2.4.3 release from PyPI?

**Comment by citosid** [comment]
Thank you. Will test.
