### ISSUE TITLE
Relative pid file paths don't work

### ISSUE THREAD

**Issue by jdelic** [thesharp/daemonize#47]
Currently daemonize will gladly accept a relative path to a pid file, then chdir to "/" and then throw an exception when it can't remove the now invalid pid file path.

A simple patch to make this work is to save the absolute path of the pid file on instantiation.
```diff
--- "..\\envs\\mn\\Lib\\site-packages\\daemonize.py"
+++ "plusdashfilter\\daemonize.py"
@@ -44,6 +44,7 @@
                  user=None, group=None, verbose=False, logger=None,
                  foreground=False, chdir="/"):
         self.app = app
+        self._pid = None
         self.pid = pid
         self.action = action
         self.keep_fds = keep_fds or []
@@ -56,6 +57,14 @@
         self.foreground = foreground
         self.chdir = chdir
 
+    @property
+    def pid(self):
+        return self._pid
+
+    @pid.setter
+    def pid(self, pid):
+        self._pid = os.path.abspath(pid)
+
     def sigterm(self, signum, frame):
         """
         These actions will be done after SIGTERM.
```

**Comment by thesharp** [comment]
Hey @jdelic.

That's a good catch, not that it's a common thing--to have relative path to the pid-file. Could you please make a pull request with that feature?

Thanks.

**Comment by knsd** [comment]
Why not `self.pid = os.path.abspath(pid)`?

**Comment by jdelic** [comment]
> Why not self.pid = os.path.abspath(pid)?
:grin: good point, I was trying out other things to see whether abspath would actually work in every configuration, but you're totally right, the above patch can just be shortened to `self.pid = os.path.abspath(pid)`

**Comment by thesharp** [comment]
@jdelic PR still welcome.
