### ISSUE TITLE
Getting Error in exit() function.

### ISSUE THREAD

**Issue by ameygat** [thesharp/daemonize#49]
This is my test code for daemonize lib
http://pastebin.com/JwrbwkSP
The code start the daemon successfully but fails to stop the deamon.
The logger seems to be not initialized ? 

I am getting error while trying to stop the daemon:
Traceback (most recent call last):
  File "dtest.py", line 27, in <module>
    daemon.exit()
  File "/usr/local/lib/python2.7/dist-packages/daemonize.py", line 70, in exit
    self.logger.warn("Stopping daemon.")
AttributeError: 'NoneType' object has no attribute 'warn'

**Comment by thesharp** [comment]
I looked over your code. You shouldn't call `exit()` directly.

**Comment by ameygat** [comment]
Then How do I stop the service ?

**Comment by thesharp** [comment]
Send a sigkill. Your daemonized code supposed to work forever. It doesn't handle stops or restarts, it isn't daemonize's concern. You should use something like `systemd` for that.
