### ISSUE TITLE
Calls to self.log.warn() should be self.log.warning()

### ISSUE THREAD

**Issue by televi** [thesharp/daemonize#61]
The log.warn() function is deprecated formally in 3.3 (and was tacitly deprecated prior to that by simply not being documented - see http://bugs.python.org/issue13235).  It would be great if Daemonize used log.warning() instead of log.warn() - I only saw calls to self.log.warn() in 3 places - sigterm(), exit(), and almost at the end of start().

**Comment by z3ntu** [comment]
Fixed by #66
