### ISSUE TITLE
Daemonizing multiple functions at once

### ISSUE THREAD

**Issue by sla-te** [thesharp/daemonize#77]
```python
from src import main
from functools import partial

for i in range(6):
	pid = f"/tmp/app_{i}.pid"
	Daemonize(app=f"app_{i}", pid=pid, action=partial(main, some_arg=True), auto_close_fds=False).start()
```
Could I make something like this work somehow? As of now It will exit after the first iteration.

**Comment by miigotu** [comment]
Use a separate script that utilizes subprocess, which calls your application with args, and parse those args to use in your daemonization.
